require('packages')
require('settings')
require('mappings')

require('packages.cmake4vim')
require('packages.colorscheme')
require('packages.telescope')
require('packages.fugitive')
require('packages.vimspector')
require('packages.nvimtree')
require('packages.neoformat')
require('packages.treesitter')
