require('packages')
require('settings')
require('mappings')

require('packages.cmake4vim')
require('packages.colorscheme')
require('packages.telescope')
require('packages.fugitive')
--require('packages.lspconfig')
require('packages.vimspector')
--require('packages.nvim-tree')
require('packages.startify')
require('packages.statusline')
